# Generated by Django 5.2.5 on 2025-08-24 16:25

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_course_id_alter_question_id_alter_result_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="excel_file",
            field=models.FileField(
                blank=True, null=True, upload_to=quiz.models.question_file_path
            ),
        ),
    ]
