# Generated by Django 5.2.5 on 2025-08-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_question_excel_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Option1", "Option1"),
                    ("Option2", "Option2"),
                    ("Option3", "Option3"),
                    ("Option4", "Option4"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="marks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
